export default {
  // MAIN
  PRIMARY: "#00C46D",
  WHITE: "#FFF",
  BACKGROUND: "#EBF5FC",
  DANGER: "#C40000",
  DANGER_DISABLED: "#DE8888",

  // FONT
  NORMAL_FONT: "#1D1D1D",

  // FIELDS
  FIELD_SHADOW: "#BABECC",
  ERROR_FIELD: "#FFD1D1",
  ERROR_FIELD_SHADOW: "#FFEBEB",
  PLACEHOLDER: "#CCC",
  ERROR_PLACEHOLDER: "#888"
};